# Global defaults for city runs (budgets, concurrency, early-stop)
# These keys align with Go types in internal/budget and Step Functions gates.
version: 1
city_defaults:
  # Early-stop and high-level budget thresholds
  early_stop:
    min_new_unique_rate: 0.05   # stop if new_unique_rate < 5% over the last window
    window: 200                 # inspection window size (calls/items)
  budgets:
    max_api_calls: 5000
    max_wall_clock_hours: 6

# Token-bucket budgets per connector
# capacity: total tokens available in the bucket
# refill: tokens added per period
# period: Go duration, e.g., "1m", "10s", "1h"
budgets:
  google.text:
    capacity: 1000
    refill: 150
    period: 1m
  google.nearby:
    capacity: 1500
    refill: 150
    period: 1m
  google.details:
    capacity: 1000
    refill: 100
    period: 1m
  overpass:
    capacity: 800
    refill: 80
    period: 1m
  otm:
    capacity: 800
    refill: 80
    period: 1m
  wiki:
    capacity: 800
    refill: 80
    period: 1m
  tavily.api:
    capacity: 1000
    refill: 100
    period: 1m
  web.fetch:
    capacity: 3000
    refill: 300
    period: 1m
  llm.tokens:
    capacity: 200000     # total token budget for extraction per run window
    refill: 0            # set to >0 to allow periodic replenishment
    period: 0s
  nominatim:
    capacity: 500
    refill: 50
    period: 1m

# 70/30 primaries/secondaries split by default (aligns with epic criteria)
split_ratio: 0.7

# Concurrency defaults (advisory; wire to orchestrator/infra as needed)
concurrency:
  web.fetch: 8
  extract.llm: 4
  geocode.validate: 4
  maps.expand_neighbors: 6
  maps.tile_sweep: 6

# Optional kill switches and circuit breakers (names only; values read at runtime)
feature_flags:
  mock_states:
    - ExtractWithLLM
    - GeocodeValidate